In [208]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [209]:
title = ['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship','race','sex','capital-gain','capital-loss','hours-per-week','native-country','income']
df_Train = pd.read_csv(r'C:\Users\USER\DataMining-hw\hw1\adult.data', names = title, header=None)
df_Test = pd.read_csv(r'C:\Users\USER\DataMining-hw\hw1\adult.test', names = title, header=None)
raw_df_train = df_Train.copy()
df_Train = df_Train.drop(columns=['fnlwgt','education-num'])
df_Test = df_Test.drop(columns=['fnlwgt','education-num'])
# 將final weight 去除(因為那是人口普查ID，ID不能被列為Feature)以及education-num
print(df_Train)
print(df_Test)

       age          workclass    education       marital-status  \
0       39          State-gov    Bachelors        Never-married   
1       50   Self-emp-not-inc    Bachelors   Married-civ-spouse   
2       38            Private      HS-grad             Divorced   
3       53            Private         11th   Married-civ-spouse   
4       28            Private    Bachelors   Married-civ-spouse   
...    ...                ...          ...                  ...   
32556   27            Private   Assoc-acdm   Married-civ-spouse   
32557   40            Private      HS-grad   Married-civ-spouse   
32558   58            Private      HS-grad              Widowed   
32559   22            Private      HS-grad        Never-married   
32560   52       Self-emp-inc      HS-grad   Married-civ-spouse   

               occupation    relationship    race      sex  capital-gain  \
0            Adm-clerical   Not-in-family   White     Male          2174   
1         Exec-managerial         Husband  

In [210]:
df_Train.replace(" ?", pd.NA, inplace=True)
df_Test.replace(" ?", pd.NA, inplace=True)
print(df_Train)
print(df_Test)

       age          workclass    education       marital-status  \
0       39          State-gov    Bachelors        Never-married   
1       50   Self-emp-not-inc    Bachelors   Married-civ-spouse   
2       38            Private      HS-grad             Divorced   
3       53            Private         11th   Married-civ-spouse   
4       28            Private    Bachelors   Married-civ-spouse   
...    ...                ...          ...                  ...   
32556   27            Private   Assoc-acdm   Married-civ-spouse   
32557   40            Private      HS-grad   Married-civ-spouse   
32558   58            Private      HS-grad              Widowed   
32559   22            Private      HS-grad        Never-married   
32560   52       Self-emp-inc      HS-grad   Married-civ-spouse   

               occupation    relationship    race      sex  capital-gain  \
0            Adm-clerical   Not-in-family   White     Male          2174   
1         Exec-managerial         Husband  

In [219]:
label_encoder = LabelEncoder()

# 將類別的相關欄位做Label Encoding
df_Train['workclass'] = label_encoder.fit_transform(df_Train['workclass'].astype('str'))
df_Test['workclass'] = label_encoder.fit_transform(df_Test['workclass'].astype('str'))

df_Train['education'] = label_encoder.fit_transform(df_Train['education'].astype('str'))
df_Test['education'] = label_encoder.fit_transform(df_Test['education'].astype('str'))

df_Train['marital-status'] = label_encoder.fit_transform(df_Train['marital-status'].astype('str'))
df_Test['marital-status'] = label_encoder.fit_transform(df_Test['marital-status'].astype('str'))

df_Train['occupation'] = label_encoder.fit_transform(df_Train['occupation'].astype('str'))
df_Test['occupation'] = label_encoder.fit_transform(df_Test['occupation'].astype('str'))

df_Train['relationship'] = label_encoder.fit_transform(df_Train['relationship'].astype('str'))
df_Test['relationship'] = label_encoder.fit_transform(df_Test['relationship'].astype('str'))

df_Train['race'] = label_encoder.fit_transform(df_Train['race'].astype('str'))
df_Test['race'] = label_encoder.fit_transform(df_Test['race'].astype('str'))

df_Train['sex'] = label_encoder.fit_transform(df_Train['sex'].astype('str'))
df_Test['sex'] = label_encoder.fit_transform(df_Test['sex'].astype('str'))

df_Train['native-country'] = label_encoder.fit_transform(df_Train['native-country'].astype('str'))
df_Test['native-country'] = label_encoder.fit_transform(df_Test['native-country'].astype('str'))

df_Train['income'] = label_encoder.fit_transform(df_Train['income'].astype('str'))
df_Test['income'] = label_encoder.fit_transform(df_Test['income'].astype('str'))

print(df_Train)

       age  workclass  education  marital-status  occupation  relationship  \
0       39          6         15               4           0             1   
1       50          5         15               2           8             0   
2       38          3          3               0          10             1   
3       53          3          1               2          10             0   
4       28          3         15               2          14             5   
...    ...        ...        ...             ...         ...           ...   
32556   27          3         13               2           4             5   
32557   40          3          3               2          11             0   
32558   58          3          3               6           0             4   
32559   22          3          3               4           0             3   
32560   52          4          3               2           8             5   

       race  sex  capital-gain  capital-loss  hours-per-week  n

In [240]:
# 將Dataframe分為X(feature)跟Y(class)
train_x = df_Train.iloc[:, 0:12].values
train_y = df_Train.iloc[:, 12].values

test_x = df_Test.iloc[:, 0:11].values
test_y = df_Test.iloc[:, 12].values
print(train_x,train_y,test_x,test_y)
# print(raw_df_train)

[[39  6 15 ...  0 40 32]
 [50  5 15 ...  0 13 32]
 [38  3  3 ...  0 40 32]
 ...
 [58  3  3 ...  0 40 32]
 [22  3  3 ...  0 20 32]
 [52  4  3 ...  0 40 32]] [0 0 0 ... 0 0 1] [[  25    3    1 ...    0    0   40]
 [  38    3    3 ...    0    0   50]
 [  28    1   13 ...    0    0   40]
 ...
 [  38    3   15 ...    0    0   50]
 [  44    3   15 ... 5455    0   40]
 [  35    4   15 ...    0    0   60]] [0 0 1 ... 0 0 1]


# CART決策樹 Python

# ID3決策樹 R

In [258]:
import rpy2.robjects as ro
import matplotlib.pyplot as plt

# 加入 rpart
rpart = ro.r('library(rpart)')

# 直接用 R 語言建立 DataFrame
df_train = ro.DataFrame(df_Train)
df_test = ro.DataFrame(df_Test)
# 在 R 中指定變數
ro.globalenv['train'] = df_train
ro.globalenv['test'] = df_test

# 建立模型及分析(ID3)
rpart_code = """

my_tree <- rpart(income~., data=train,method="class",maxdepth=10)

dev.list()
pdf("r-graph.pdf")
dev.cur()
plot(my_tree,faclen=0,fallen.leaves=TRUE,shadow.col="gray",extra=2)
dev.off()

pred <- predict(my_tree, newdata=test, type="matrix")

"""
ro.r(rpart_code)

# 将模型转换为 Python 数据结构
# model_summary = ro.r('summary(my_tree)')
# print(model_summary)

# 將 R 語言中的圖表轉換為 Python 語言
pred = ro.r('pred')

# [TP,FN,FP,TN]
c_matrix=[0,0,0,0]
for i in range(len(test_y)):
    if int(pred[i][0]) - 1 == test_y[i] and test_y[i] == 1:
        c_matrix[0] += 1
    elif int(pred[i][0]) - 1 != test_y[i] and test_y[i] == 1:
        c_matrix[1] += 1
    elif int(pred[i][0]) - 1 != test_y[i] and test_y[i] == 0:
        c_matrix[2] += 1
    elif int(pred[i][0]) - 1 == test_y[i] and test_y[i] == 0:
        c_matrix[3] += 1
print("maxdepth=",c_matrix,end="")
print("acc=",(c_matrix[0]+c_matrix[3])/(c_matrix[0]+c_matrix[1]+c_matrix[2]+c_matrix[3]))

maxdepth= [1790, 2056, 580, 11855]acc= 0.8380934832012775


# C4.5決策樹 R

In [253]:
import rpy2.robjects as ro
import matplotlib.pyplot as plt

# 加入 rpart
rpart = ro.r('library(rpart)')

# 直接用 R 語言建立 DataFrame
df_train = ro.DataFrame(df_Train)
df_test = ro.DataFrame(df_Test)
# 在 R 中指定變數
ro.globalenv['train'] = df_train
ro.globalenv['test'] = df_test
print(df_Train['income'].dtypes)
# 建立模型及分析(ID3)
rpart_code = """

library(RWeka)
library("partykit")

train$income <- as.factor(train$income)
my_tree <- J48(income~., data=train,control=Weka_control(M=2))
ttncTree<-as.party(my_tree)
plot(ttncTree)
test$income <- as.factor(test$income)
pred <- predict(my_tree, newdata=test, type="probability")

"""
ro.r(rpart_code)
model_summary = ro.r('summary(my_tree)')
print(model_summary)
wow = ro.r('WOW(J48)')
print(wow)
# 如果你需要将处理后的数据从R传回Python，你可以这样做：
# result_in_r = ro.globalenv['str(iris)']
# result_in_r

# 將 R 語言中的圖表轉換為 Python 語言
p = ro.r('pred')
# print(pred)
pred = []
for i in range(len(p)):
    if p[i][0] >= p[i][1]:
        pred.append(0)
    else:
        pred.append(1)
print(pred.count(0))


# [TP,FN,FP,TN]
c_matrix=[0,0,0,0] 
for i in range(len(test_y)):
    if int(pred[i]) == test_y[i] and test_y[i] == 1:
        c_matrix[0] += 1
    elif int(pred[i]) != test_y[i] and test_y[i] == 1:
        c_matrix[1] += 1
    elif int(pred[i]) != test_y[i] and test_y[i] == 0:
        c_matrix[2] += 1
    elif int(pred[i]) == test_y[i] and test_y[i] == 0:
        c_matrix[3] += 1
print("maxdepth=",c_matrix,end="")
print("acc=",(c_matrix[0]+c_matrix[3])/(c_matrix[0]+c_matrix[1]+c_matrix[2]+c_matrix[3]))

int32


=== Summary ===



Correctly Classified Instances       28665               88.0348 %

Incorrectly Classified Instances      3896               11.9652 %

Kappa statistic                          0.6548

Mean absolute error                      0.1828

Root mean squared error                  0.3023

Relative absolute error                 49.9889 %

Root relative squared error             70.7036 %

Total Number of Instances            32561     



=== Confusion Matrix ===



     a     b   <-- classified as

 23371  1349 |     a = 0

  2547  5294 |     b = 1

-U      Use unpruned tree.

-O      Do not collapse tree.

-C <pruning confidence>

        Set confidence threshold for pruning.  (default 0.25)

	Number of arguments: 1.

-M <minimum number of instances>

        Set minimum number of instances per leaf.  (default 2)

	Number of arguments: 1.

-R      Use reduced error pruning.

-N <number of folds>

        Set number of folds for reduced error pruning. One fold is u

In [ ]:
# [TP,FN,FP,TN]
# c_matrix=[0,0,0,0] 
# for i in range(len(test_y)):
#     if int(pred[i][0]) - 1 == test_y[i] and test_y[i] == 1:
#         c_matrix[0] += 1
#     elif int(pred[i][0]) - 1 != test_y[i] and test_y[i] == 1:
#         c_matrix[1] += 1
#     elif int(pred[i][0]) - 1 != test_y[i] and test_y[i] == 0:
#         c_matrix[2] += 1
#     elif int(pred[i][0]) - 1 == test_y[i] and test_y[i] == 0:
#         c_matrix[3] += 1
# print("maxdepth=",c_matrix,end="")
# print("acc=",(c_matrix[0]+c_matrix[3])/(c_matrix[0]+c_matrix[1]+c_matrix[2]+c_matrix[3]))