In [116]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [117]:
title = ['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship','race','sex','capital-gain','capital-loss','hours-per-week','native-country','income']
df_Train = pd.read_csv(r'C:\Users\USER\DataMining-hw\hw1\adult.data', names = title, header=None)
df_Test = pd.read_csv(r'C:\Users\USER\DataMining-hw\hw1\adult.test', names = title, header=None)
raw_df_train = df_Train.copy()
df_Train = df_Train.drop(columns=['fnlwgt','education-num'])
df_Test = df_Test.drop(columns=['fnlwgt','education-num'])
# 將final weight 去除(因為那是人口普查ID，ID不能被列為Feature)以及education-num
print(df_Train)
print(df_Test)

       age          workclass    education       marital-status  \
0       39          State-gov    Bachelors        Never-married   
1       50   Self-emp-not-inc    Bachelors   Married-civ-spouse   
2       38            Private      HS-grad             Divorced   
3       53            Private         11th   Married-civ-spouse   
4       28            Private    Bachelors   Married-civ-spouse   
...    ...                ...          ...                  ...   
32556   27            Private   Assoc-acdm   Married-civ-spouse   
32557   40            Private      HS-grad   Married-civ-spouse   
32558   58            Private      HS-grad              Widowed   
32559   22            Private      HS-grad        Never-married   
32560   52       Self-emp-inc      HS-grad   Married-civ-spouse   

               occupation    relationship    race      sex  capital-gain  \
0            Adm-clerical   Not-in-family   White     Male          2174   
1         Exec-managerial         Husband  

In [118]:
df_Train.replace(" ?", pd.NA, inplace=True)
df_Test.replace(" ?", pd.NA, inplace=True)
print(df_Train)
print(df_Test)

       age          workclass    education       marital-status  \
0       39          State-gov    Bachelors        Never-married   
1       50   Self-emp-not-inc    Bachelors   Married-civ-spouse   
2       38            Private      HS-grad             Divorced   
3       53            Private         11th   Married-civ-spouse   
4       28            Private    Bachelors   Married-civ-spouse   
...    ...                ...          ...                  ...   
32556   27            Private   Assoc-acdm   Married-civ-spouse   
32557   40            Private      HS-grad   Married-civ-spouse   
32558   58            Private      HS-grad              Widowed   
32559   22            Private      HS-grad        Never-married   
32560   52       Self-emp-inc      HS-grad   Married-civ-spouse   

               occupation    relationship    race      sex  capital-gain  \
0            Adm-clerical   Not-in-family   White     Male          2174   
1         Exec-managerial         Husband  

In [119]:
label_encoder = LabelEncoder()

# 將類別的相關欄位做Label Encoding
df_Train['workclass'] = label_encoder.fit_transform(df_Train['workclass'].astype('str'))
df_Test['workclass'] = label_encoder.fit_transform(df_Test['workclass'].astype('str'))

df_Train['education'] = label_encoder.fit_transform(df_Train['education'].astype('str'))
df_Test['education'] = label_encoder.fit_transform(df_Test['education'].astype('str'))

df_Train['marital-status'] = label_encoder.fit_transform(df_Train['marital-status'].astype('str'))
df_Test['marital-status'] = label_encoder.fit_transform(df_Test['marital-status'].astype('str'))

df_Train['occupation'] = label_encoder.fit_transform(df_Train['occupation'].astype('str'))
df_Test['occupation'] = label_encoder.fit_transform(df_Test['occupation'].astype('str'))

df_Train['relationship'] = label_encoder.fit_transform(df_Train['relationship'].astype('str'))
df_Test['relationship'] = label_encoder.fit_transform(df_Test['relationship'].astype('str'))

df_Train['race'] = label_encoder.fit_transform(df_Train['race'].astype('str'))
df_Test['race'] = label_encoder.fit_transform(df_Test['race'].astype('str'))

df_Train['sex'] = label_encoder.fit_transform(df_Train['sex'].astype('str'))
df_Test['sex'] = label_encoder.fit_transform(df_Test['sex'].astype('str'))

df_Train['native-country'] = label_encoder.fit_transform(df_Train['native-country'].astype('str'))
df_Test['native-country'] = label_encoder.fit_transform(df_Test['native-country'].astype('str'))

df_Train['income'] = label_encoder.fit_transform(df_Train['income'].astype('str'))
df_Test['income'] = label_encoder.fit_transform(df_Test['income'].astype('str'))

print(df_Train)

       age  workclass  education  marital-status  occupation  relationship  \
0       39          6          9               4           0             1   
1       50          5          9               2           3             0   
2       38          3         11               0           5             1   
3       53          3          1               2           5             0   
4       28          3          9               2           9             5   
...    ...        ...        ...             ...         ...           ...   
32556   27          3          7               2          12             5   
32557   40          3         11               2           6             0   
32558   58          3         11               6           0             4   
32559   22          3         11               4           0             3   
32560   52          4         11               2           3             5   

       race  sex  capital-gain  capital-loss  hours-per-week  n

In [120]:
# 將Dataframe分為X(feature)跟Y(class)
train_x = df_Train.iloc[:, 0:12].values
train_y = df_Train.iloc[:, 12].values

test_x = df_Test.iloc[:, 0:11].values
test_y = df_Test.iloc[:, 12].values
print(train_x,train_y,test_x,test_y)
# print(raw_df_train)

[[39  6  9 ...  0 40 38]
 [50  5  9 ...  0 13 38]
 [38  3 11 ...  0 40 38]
 ...
 [58  3 11 ...  0 40 38]
 [22  3 11 ...  0 20 38]
 [52  4 11 ...  0 40 38]] [0 0 0 ... 0 0 1] [[  25    3    1 ...    0    0   40]
 [  38    3   11 ...    0    0   50]
 [  28    1    7 ...    0    0   40]
 ...
 [  38    3    9 ...    0    0   50]
 [  44    3    9 ... 5455    0   40]
 [  35    4    9 ...    0    0   60]] [0 0 1 ... 0 0 1]


In [153]:
import rpy2.robjects as ro
import matplotlib.pyplot as plt

# 加入 rpart
rpart = ro.r('library(rpart)')

# 直接用 R 語言建立 DataFrame
df_train = ro.DataFrame(df_Train)
df_test = ro.DataFrame(df_Test)
# 在 R 中指定變數
ro.globalenv['train'] = df_train
ro.globalenv['test'] = df_test

# 建立模型及分析(ID3)
rpart_code = """

my_tree <- rpart(income~., data=train,method="class",maxdepth=10)

dev.list()
pdf("r-graph.pdf")
dev.cur()
plot(my_tree,faclen=0,fallen.leaves=TRUE,shadow.col="gray",extra=2)
dev.off()

pred <- predict(my_tree, newdata=test, type="matrix")

"""
ro.r(rpart_code)

# 将模型转换为 Python 数据结构
# model_summary = ro.r('summary(my_tree)')
# print(model_summary)

# 將 R 語言中的圖表轉換為 Python 語言
pred = ro.r('pred')

# [TP,FN,FP,TN]
c_matrix=[0,0,0,0] 
for i in range(len(test_y)):
    if int(pred[i][0]) - 1 == test_y[i] and test_y[i] == 1:
        c_matrix[0] += 1
    elif int(pred[i][0]) - 1 != test_y[i] and test_y[i] == 1:
        c_matrix[1] += 1
    elif int(pred[i][0]) - 1 != test_y[i] and test_y[i] == 0:
        c_matrix[2] += 1
    elif int(pred[i][0]) - 1 == test_y[i] and test_y[i] == 0:
        c_matrix[3] += 1
print("maxdepth=",c_matrix,end="")
print("acc=",(c_matrix[0]+c_matrix[3])/(c_matrix[0]+c_matrix[1]+c_matrix[2]+c_matrix[3]))

maxdepth= [1904, 1942, 621, 11814]acc= 0.842577237270438


In [152]:
import rpy2.robjects as ro
import matplotlib.pyplot as plt

# 加载 rpart 包
rpart = ro.r('library(rpart)')

# 直接用 R 語言建立 DataFrame
df_train = ro.DataFrame(df_Train)
df_test = ro.DataFrame(df_Test)
# 在 R 中使用数据
ro.globalenv['train'] = df_train
ro.globalenv['test'] = df_test

# 在 R 中定义 target 变量
rpart_code = """

my_tree <- rpart(income~., data=train,method="class",maxdepth=10)

dev.list()
pdf("r-graph.pdf")
dev.cur()
plot(my_tree,faclen=0,fallen.leaves=TRUE,shadow.col="gray",extra=2)
dev.off()

pred <- predict(my_tree, newdata=test, type="matrix")

"""
ro.r(rpart_code)

# 从 R 中提取决策树模型
rpart_model = ro.globalenv['my_r_data']

# 将模型转换为 Python 数据结构
model_summary = ro.r('summary(my_tree)')
print(model_summary)

# 將 R 語言中的圖表轉換為 Python 語言
pred = ro.r('pred')

# [TP,FN,FP,TN]
c_matrix=[0,0,0,0] 
for i in range(len(test_y)):
    if int(pred[i][0]) - 1 == test_y[i] and test_y[i] == 1:
        c_matrix[0] += 1
    elif int(pred[i][0]) - 1 != test_y[i] and test_y[i] == 1:
        c_matrix[1] += 1
    elif int(pred[i][0]) - 1 != test_y[i] and test_y[i] == 0:
        c_matrix[2] += 1
    elif int(pred[i][0]) - 1 == test_y[i] and test_y[i] == 0:
        c_matrix[3] += 1
print("maxdepth=",c_matrix,end="")
print("acc=",(c_matrix[0]+c_matrix[3])/(c_matrix[0]+c_matrix[1]+c_matrix[2]+c_matrix[3]))


n= 32561 



node), split, n, loss, yval, (yprob)

      * denotes terminal node



  1) root 32561 7841 0 (0.75919044 0.24080956)  

    2) relationship>=0.5 19368 1923 0 (0.90071252 0.09928748)  

      4) capital.gain< 7073.5 18932 1501 0 (0.92071625 0.07928375) *

      5) capital.gain>=7073.5 436   14 1 (0.03211009 0.96788991) *

    3) relationship< 0.5 13193 5918 0 (0.55142879 0.44857121)  

      6) capital.gain< 5095.5 12122 4858 0 (0.59924105 0.40075895)  

       12) capital.loss< 1782.5 11434 4273 0 (0.62629001 0.37370999)  

         24) education< 6.5 1414  137 0 (0.90311174 0.09688826) *

         25) education>=6.5 10020 4136 0 (0.58722555 0.41277445)  

           50) education>=10.5 7058 2505 0 (0.64508359 0.35491641)  

            100) education< 11.5 3939 1044 0 (0.73495811 0.26504189) *

            101) education>=11.5 3119 1461 0 (0.53158063 0.46841937)  

              202) education>=14.5 2209  830 0 (0.62426437 0.37573563) *

              203) education< 14.