In [77]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [78]:
title = ['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship','race','sex','capital-gain','capital-loss','hours-per-week','native-country','income']
df_Train = pd.read_csv(r'C:\Users\USER\DataMining-hw\hw1\adult.data', names = title, header=None,encoding='unicode_escape')
df_Test = pd.read_csv(r'C:\Users\USER\DataMining-hw\hw1\adult.test', names = title, header=None)
raw_df_train = df_Train.copy()
df_Train = df_Train.drop(columns=['fnlwgt','education-num'])
df_Test = df_Test.drop(columns=['fnlwgt','education-num'])
# 將final weight 去除(因為那是人口普查ID，ID不能被列為Feature)以及education-num
print(df_Train)
print(df_Test)

       age          workclass    education       marital-status  \
0       39          State-gov    Bachelors        Never-married   
1       50   Self-emp-not-inc    Bachelors   Married-civ-spouse   
2       38            Private      HS-grad             Divorced   
3       53            Private         11th   Married-civ-spouse   
4       28            Private    Bachelors   Married-civ-spouse   
...    ...                ...          ...                  ...   
32556   27            Private   Assoc-acdm   Married-civ-spouse   
32557   40            Private      HS-grad   Married-civ-spouse   
32558   58            Private      HS-grad              Widowed   
32559   22            Private      HS-grad        Never-married   
32560   52       Self-emp-inc      HS-grad   Married-civ-spouse   

               occupation    relationship    race      sex  capital-gain  \
0            Adm-clerical   Not-in-family   White     Male          2174   
1         Exec-managerial         Husband  

In [79]:
df_Train.replace(" ?", pd.NA, inplace=True)
df_Test.replace(" ?", pd.NA, inplace=True)
print(df_Train)
print(df_Test)

       age          workclass    education       marital-status  \
0       39          State-gov    Bachelors        Never-married   
1       50   Self-emp-not-inc    Bachelors   Married-civ-spouse   
2       38            Private      HS-grad             Divorced   
3       53            Private         11th   Married-civ-spouse   
4       28            Private    Bachelors   Married-civ-spouse   
...    ...                ...          ...                  ...   
32556   27            Private   Assoc-acdm   Married-civ-spouse   
32557   40            Private      HS-grad   Married-civ-spouse   
32558   58            Private      HS-grad              Widowed   
32559   22            Private      HS-grad        Never-married   
32560   52       Self-emp-inc      HS-grad   Married-civ-spouse   

               occupation    relationship    race      sex  capital-gain  \
0            Adm-clerical   Not-in-family   White     Male          2174   
1         Exec-managerial         Husband  

In [80]:
label_encoder = LabelEncoder()

# 將類別的相關欄位做Label Encoding
df_Train['workclass'] = label_encoder.fit_transform(df_Train['workclass'].astype('str'))
df_Test['workclass'] = label_encoder.fit_transform(df_Test['workclass'].astype('str'))

df_Train['education'] = label_encoder.fit_transform(df_Train['education'].astype('str'))
df_Test['education'] = label_encoder.fit_transform(df_Test['education'].astype('str'))

df_Train['marital-status'] = label_encoder.fit_transform(df_Train['marital-status'].astype('str'))
df_Test['marital-status'] = label_encoder.fit_transform(df_Test['marital-status'].astype('str'))

df_Train['occupation'] = label_encoder.fit_transform(df_Train['occupation'].astype('str'))
df_Test['occupation'] = label_encoder.fit_transform(df_Test['occupation'].astype('str'))

df_Train['relationship'] = label_encoder.fit_transform(df_Train['relationship'].astype('str'))
df_Test['relationship'] = label_encoder.fit_transform(df_Test['relationship'].astype('str'))

df_Train['race'] = label_encoder.fit_transform(df_Train['race'].astype('str'))
df_Test['race'] = label_encoder.fit_transform(df_Test['race'].astype('str'))

df_Train['sex'] = label_encoder.fit_transform(df_Train['sex'].astype('str'))
df_Test['sex'] = label_encoder.fit_transform(df_Test['sex'].astype('str'))

df_Train['native-country'] = label_encoder.fit_transform(df_Train['native-country'].astype('str'))
df_Test['native-country'] = label_encoder.fit_transform(df_Test['native-country'].astype('str'))

# df_Train['income'] = label_encoder.fit_transform(df_Train['income'].astype('str'))
# df_Test['income'] = label_encoder.fit_transform(df_Test['income'].astype('str'))

print(df_Train)

       age  workclass  education  marital-status  occupation  relationship  \
0       39          6          9               4           0             1   
1       50          5          9               2           3             0   
2       38          3         11               0           5             1   
3       53          3          1               2           5             0   
4       28          3          9               2           9             5   
...    ...        ...        ...             ...         ...           ...   
32556   27          3          7               2          12             5   
32557   40          3         11               2           6             0   
32558   58          3         11               6           0             4   
32559   22          3         11               4           0             3   
32560   52          4         11               2           3             5   

       race  sex  capital-gain  capital-loss  hours-per-week  n

In [81]:
# 將Dataframe分為X(feature)跟Y(class)
train_x = df_Train.iloc[:, 0:12].values
train_y = df_Train.iloc[:, 12].values

test_x = df_Test.iloc[:, 0:12].values
test_y = df_Test.iloc[:, 12].values
print(train_x,train_y,test_x,test_y)
# print(raw_df_train)

[[39  6  9 ...  0 40 38]
 [50  5  9 ...  0 13 38]
 [38  3 11 ...  0 40 38]
 ...
 [58  3 11 ...  0 40 38]
 [22  3 11 ...  0 20 38]
 [52  4 11 ...  0 40 38]] [' <=50K' ' <=50K' ' <=50K' ... ' <=50K' ' <=50K' ' >50K'] [[25  3  1 ...  0 40 37]
 [38  3 11 ...  0 50 37]
 [28  1  7 ...  0 40 37]
 ...
 [38  3  9 ...  0 50 37]
 [44  3  9 ...  0 40 37]
 [35  4  9 ...  0 60 37]] [' <=50K' ' <=50K' ' >50K' ... ' <=50K' ' <=50K' ' >50K']


# CART決策樹 Python

In [82]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree
from sklearn.metrics import confusion_matrix
from six import StringIO

import pydot
import pydotplus
import matplotlib.pyplot as plt
# 訓練CART決策樹
result=[]

# train1 max_depth = 7,max_leaf_nodes=61
model1 = DecisionTreeClassifier(criterion='gini',max_depth=7,max_leaf_nodes=61).fit(train_x,train_y)
result.append(model1.score(train_x,train_y))
# train2 max_depth = 9,max_leaf_nodes=81
model2 = DecisionTreeClassifier(criterion='gini',max_depth=9,max_leaf_nodes=81).fit(train_x,train_y)
result.append(model2.score(train_x,train_y))
# train3 max_depth = 11,max_leaf_nodes=90
model3 = DecisionTreeClassifier(criterion='gini',max_depth=11,max_leaf_nodes=90).fit(train_x,train_y)
result.append(model3.score(train_x,train_y))
# train4 raw
model4 = DecisionTreeClassifier(criterion='gini').fit(train_x,train_y)
result.append(model4.score(train_x,train_y))
model=[model1,model2,model3,model4]
for i in range(4):
    print(result[i])
for i in range(4):
    print(model[i].score(test_x,test_y))

# 使用測試集預測
# model.predict(test_x)
# model.score(test_x,test_y)

# 計算混淆矩陣
cm1 = confusion_matrix(test_y, model1.predict(test_x))
cm2 = confusion_matrix(test_y, model2.predict(test_x))
cm3 = confusion_matrix(test_y, model3.predict(test_x))
cm4 = confusion_matrix(test_y, model4.predict(test_x))
print(cm1)
print(cm2)
print(cm3)
print(cm4)

# 畫出樹的圖到PNG
def print_png(model: str,png_name: str):
    title = ['age','workclass','education-num','marital-status','occupation','relationship','race','sex','capital-gain','capital-loss','hours-per-week','native-country']

    dot_data = StringIO()
    tree.export_graphviz(model,
            out_file=dot_data,
            feature_names=title,
            class_names="10",
            filled=True, rounded=True,
            impurity=False)

    graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
    graph.write_png(png_name)
# print_png(model1,r"C:\Users\USER\DataMining-hw\hw1\adult7-61.png")
# print_png(model2,r"C:\Users\USER\DataMining-hw\hw1\adult9-81.png")
# print_png(model3,r"C:\Users\USER\DataMining-hw\hw1\adult11-90.png")
# print_pdf(model4,r"C:\Users\USER\DataMining-hw\hw1\adult-raw.png")

0.8546113448604158
0.8595866220324928
0.863087743005436
0.976413500813857
0.85283459246975
0.8562127633437749
0.8549229162827836
0.8185615134205516
[[11836   599]
 [ 1797  2049]]
[[11781   654]
 [ 1687  2159]]
[[11666   769]
 [ 1593  2253]]
[[11023  1412]
 [ 1542  2304]]


# ID3決策樹 R

In [87]:
import os
os.environ['R_HOME'] = r'C:\Users\USER\anaconda3\envs\testhw\Lib\R'


import rpy2.robjects as ro
import matplotlib.pyplot as plt
from rpy2.robjects import pandas2ri
# 要加這個activate，不然無法匯入dataframe到R語言中
pandas2ri.activate()
# 加入 rpart
rpart = ro.r('library(rpart)')

# 直接用 R 語言建立 DataFrame
df_train = ro.DataFrame(df_Train)
df_test = ro.DataFrame(df_Test)
# 在 R 中指定變數
ro.globalenv['train'] = df_train
ro.globalenv['test'] = df_test

# 訓練模型、繪圖、預測(ID3)
rpart_code = """
library(rpart.plot)

my_tree <- rpart(income~., data=train,method="class",control = rpart.control(minsplit=1,cp=0.03))
train_index <- sample(1:32561, size = 32561, replace = FALSE)
income_train <- train$income[train_index]
(train_table <- table(train = train$income[train_index],predict = predict(my_tree, newdata=train, type="class")))
train_acc=sum(diag(train_table))/sum(train_table)

dev.list()
pdf("r-graph.pdf")
dev.cur()
prp(my_tree,faclen=0,fallen.leaves=TRUE,shadow.col="gray",extra=2,cex = 1) 
dev.off()

pred <- predict(my_tree, newdata=test, type="matrix")

"""
ro.r(rpart_code)

# Summary 結果顯示
model_summary = ro.r('summary(my_tree)')
print(model_summary)

# 將 R 語言中的圖表轉換為 Python 語言
pred = ro.r('pred')
train_table = ro.r('train_table')
print(train_table)

# [TP,FN,FP,TN] 計算時將test_y轉為[0,1]
c_matrix=[0,0,0,0]
df_Train['income'] = label_encoder.fit_transform(df_Train['income'].astype('str'))
df_Test['income'] = label_encoder.fit_transform(df_Test['income'].astype('str'))
test_y = df_Test.iloc[:, 12].values
print(df_Train)
for i in range(len(test_y)):
    if int(pred[i][0]) - 1 == test_y[i] and test_y[i] == 1:
        c_matrix[0] += 1
    elif int(pred[i][0]) - 1 != test_y[i] and test_y[i] == 1:
        c_matrix[1] += 1
    elif int(pred[i][0]) - 1 != test_y[i] and test_y[i] == 0:
        c_matrix[2] += 1
    elif int(pred[i][0]) - 1 == test_y[i] and test_y[i] == 0:
        c_matrix[3] += 1
train_acc = ro.r('train_acc')
print("train_acc=",train_acc)
print(c_matrix,end="")
print("test_acc=",(c_matrix[0]+c_matrix[3])/(c_matrix[0]+c_matrix[1]+c_matrix[2]+c_matrix[3]))

n= 32561 



node), split, n, loss, yval, (yprob)

      * denotes terminal node



 1) root 32561 7841 0 (0.75919044 0.24080956)  

   2) relationship>=0.5 19368 1923 0 (0.90071252 0.09928748)  

     4) capital.gain< 7073.5 18932 1501 0 (0.92071625 0.07928375) *

     5) capital.gain>=7073.5 436   14 1 (0.03211009 0.96788991) *

   3) relationship< 0.5 13193 5918 0 (0.55142879 0.44857121)  

     6) capital.gain< 5095.5 12122 4858 0 (0.59924105 0.40075895)  

      12) capital.loss< 1782.5 11434 4273 0 (0.62629001 0.37370999) *

      13) capital.loss>=1782.5 688  103 1 (0.14970930 0.85029070) *

     7) capital.gain>=5095.5 1071   11 1 (0.01027077 0.98972923) *

[[23051  1669]
 [ 7315   526]]
       age  workclass  education  marital-status  occupation  relationship  \
0       39          6          9               4           0             1   
1       50          5          9               2           3             0   
2       38          3         11               0           5 

# C4.5決策樹 R

In [90]:
import rpy2.robjects as ro
import matplotlib.pyplot as plt
from rpy2.robjects import pandas2ri
# 要加這個activate，不然無法匯入dataframe到R語言中
pandas2ri.activate()
# 加入 rpart
rpart = ro.r('library(rpart)')

# 直接用 R 語言建立 DataFrame
df_train = ro.DataFrame(df_Train)
df_test = ro.DataFrame(df_Test)
# 在 R 中指定變數
ro.globalenv['train'] = df_train
ro.globalenv['test'] = df_test
print(df_Train['income'].dtypes)

# import套件、訓練模型、繪圖、預測(C4.5)
rpart_code = """

library(RWeka)

train$income <- as.factor(train$income)
my_tree <- J48(income~., data=train,control=Weka_control(U=F,M=10,R=T))


dev.list()
pdf("c-graph.pdf",width=150,height=40)
dev.cur()
plot(my_tree,tnex=T,type="simple")
dev.off()

test$income <- as.factor(test$income)
pred <- predict(my_tree, newdata=test, type="probability")

"""
ro.r(rpart_code)
# model_summary = ro.r('summary(my_tree)')
# print(model_summary)
# my_tree = ro.r('my_tree')
# print(my_tree)
# WOW 查看可以調的參數
# wow = ro.r('WOW(J48)')
# print(wow)

# 將 R 語言中的圖表轉換為 Python 語言
p = ro.r('pred')
# print(pred)
pred = []
for i in range(len(p)):
    if p[i][0] >= p[i][1]:
        pred.append(0)
    else:
        pred.append(1)
print(pred.count(0))


# [TP,FN,FP,TN]
c_matrix=[0,0,0,0] 
for i in range(len(test_y)):
    if int(pred[i]) == test_y[i] and test_y[i] == 1:
        c_matrix[0] += 1
    elif int(pred[i]) != test_y[i] and test_y[i] == 1:
        c_matrix[1] += 1
    elif int(pred[i]) != test_y[i] and test_y[i] == 0:
        c_matrix[2] += 1
    elif int(pred[i]) == test_y[i] and test_y[i] == 0:
        c_matrix[3] += 1
print(c_matrix,end="")
print("test_acc=",(c_matrix[0]+c_matrix[3])/(c_matrix[0]+c_matrix[1]+c_matrix[2]+c_matrix[3]))

int32
13419
[2202, 1644, 660, 11775]test_acc= 0.8584853510226644


# C5.0決策樹 R

In [91]:
import rpy2.robjects as ro
import matplotlib.pyplot as plt
from rpy2.robjects import pandas2ri
from rpy2.robjects.packages import importr
# 要加這個activate，不然無法匯入dataframe到R語言中
pandas2ri.activate()

# 直接用 R 語言建立 DataFrame
df_train = ro.DataFrame(df_Train)
df_test = ro.DataFrame(df_Test)
# 在 R 中指定變數
ro.globalenv['train'] = df_train
ro.globalenv['test'] = df_test

# 訓練C5.0決策樹、用測試集預測
rpart_code = """
library(C50)

train$income <- as.factor(train$income)
c50_tree = C5.0(income~.,train)


pred <- predict(c50_tree, newdata=test, type="prob")

"""
ro.r(rpart_code)

# 轉換test_y為數值計算混淆矩陣
df_Test['income'] = label_encoder.fit_transform(df_Test['income'].astype('str'))
test_y = df_Test.iloc[:, 12].values

# 看訓練結果
model_summary = ro.r('summary(c50_tree)')
print(model_summary)

# 將 R 語言中的pred取出來
p = ro.r('pred')
print(pred)

# [TP,FN,FP,TN]
c_matrix=[0,0,0,0]
for i in range(len(test_y)):
    if int(pred[i]) == test_y[i] and test_y[i] == 1:
        c_matrix[0] += 1
    elif int(pred[i]) != test_y[i] and test_y[i] == 1:
        c_matrix[1] += 1
    elif int(pred[i]) != test_y[i] and test_y[i] == 0:
        c_matrix[2] += 1
    elif int(pred[i]) == test_y[i] and test_y[i] == 0:
        c_matrix[3] += 1
print("maxdepth=",c_matrix,end="")
print("test_acc=",(c_matrix[0]+c_matrix[3])/(c_matrix[0]+c_matrix[1]+c_matrix[2]+c_matrix[3]))



Call:

C5.0.formula(formula = income ~ ., data = train)





C5.0 [Release 2.07 GPL Edition]  	Wed Oct 25 03:10:30 2023

-------------------------------



Class specified by attribute `outcome'



Read 32561 cases (13 attributes) from undefined.data



Decision tree:



capital.gain > 6849: 1 (1399/20)

capital.gain <= 6849:

:...capital.loss > 1816:

    :...marital.status > 2:

    :   :...capital.loss <= 2206: 0 (87)

    :   :   capital.loss > 2206:

    :   :   :...native.country <= 37: 0 (4)

    :   :       native.country > 37:

    :   :       :...capital.loss <= 2352: 0 (31/12)

    :   :           capital.loss > 2352:

    :   :           :...capital.loss <= 3683: 1 (30/1)

    :   :               capital.loss > 3683: 0 (5)

    :   marital.status <= 2:

    :   :...capital.loss <= 1977:

    :       :...marital.status <= 1: 0 (19)

    :       :   marital.status > 1: 1 (585/14)

    :       capital.loss > 1977:

    :       :...capital.loss <= 2163: 0 (73)

    :         

# 將結果匯出到Excel

In [ ]:

import numpy as np
import pandas as pd

# 創建兩個 DataFrame
df1 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6]]))
df2 = pd.DataFrame(np.array([[7, 8, 9], [10, 11, 12]]))

# 創建一個 ExcelWriter 對象
writer = pd.ExcelWriter("matrix.xlsx")

# 將 DataFrame 保存到不同的工作表
df1.to_excel(writer, sheet_name="sheet1")
df2.to_excel(writer, sheet_name="sheet2")

# 保存 Excel 文件
writer.save()
